openapi: '3.0'
info:
  version: 1.0
  title: MyChem.info API
  description: >-
    Documentation of the MyChem.info Chemical Query web services. Learn more about
    [MyChem.info](http://mychem.info/)
servers:
  url: 'http://mychem.info/v1'
paths:
  /query:
    get:
      description: Makes chemical query and returns matching chemicals list.
      parameters:
        - name: q
          in: query
          description: >-
            Query string. Examples "Fludara", "CHEMBI:63599", "DB01073". 
          required: true
          x-valueType:
            - 'http://schema.org/rxcui'
            - 'http://identifiers.org/chebi/'
            - 'http://identifiers.org/chembl/'
            - 'http://identifiers.org/drugbank/'
            - 'http://identifiers.org/iuphar.ligand/
            - 'http://identifiers.org/kegg.drug/'
            - 'http://identifiers.org/kegg.compound/'
            - 'http://identifiers.org/pubchem.compound/'
            - 'http://identifiers.org/unii/'
            - 'http://identifiers.org/inchikey/'
            - 'http://identifiers.org/inchi/'
            - 'http://identifiers.org/uniprot'
          x-requestTemplate:
            'http://schema.org/rxcui':
              /query?q=aeolus.rxcui:{{input}} OR drugcentral.xref.rxnorm:{{input}} OR ginas.xrefs.RXCUI:{{input}} OR pharmgkb.external_vocabulary.rxnorm:{{input}}
            'http://identifiers.org/chebi/':
              /query?q=drugcentral.xref.chebi:{{input}} OR chebi.chebi_id:{{input}}
            'http://identifiers.org/chembl/':
              /query?q=chembl.molecule_chembl_id:{{input}} OR drugbank.chembl:{{input}} OR drugcentral.xref.chembl_id:{{input}}
            'http://identifiers.org/drugbank/':
              /query?q=drugcentral.xref.drugbank_id:{{input}} OR pharmgkb.cross_references.drugbank:{{input}} OR drugbank.accession_number:{{input}} OR chebi.drugbank_database_links:{{input}}
            'http://identifiers.org/iuphar.ligand/':
              /query?q=drugcentral.xref.iuphar_ligand_id:{{input}} OR pharmgkb.cross_references.iuphar_ligand:{{input}}
            'http://identifiers.org/kegg.drug/':
              /query?q=drugcentral.xref.kegg_drug:{{input}} OR chebi.kegg_drug_database_links:{{input}} OR drugbank.kegg_drug:{{input}} OR pharmgkb.cross_references.kegg_drug:{{input}}
            'http://identifiers.org/kegg.compound/':
              /query?q=chebi.kegg_compound_database_links:{{input}} OR pharmgkb.cross_references.kegg_compound:{{input}}
            'http://identifiers.org/pubchem.compound/':
              /query?q=drugcentral.xref.pubchem_cid:{{input}} OR chebi.pubchem_database_links:{{input}} OR pharmgkb.cross_references.pubchem_compound:{{input}} OR pubchem.cid:{{input}}
            'http://identifiers.org/unii/':
              /query?q=drugcentral.xref.unii:{{input}} OR aeolus.unii:{{input}} OR ginas.unii:{{input}} OR unii.unii:{{input}}
            'http://identifiers.org/inchikey/':
              /query?q=aeolus.inchikey:{{input}} OR chebi.inchikey:{{input}} OR chembl.inchi_key:{{input}} OR drugbank.inchi_key:{{input}} OR drugcentral.structures.inchikey:{{input}} OR ginas.inchikey:{{input}} OR pubchem.inchi_key:{{input}} OR unii.inchikey:{{input}}
            'http://identifiers.org/inchi/':
              /query?q=pubchem.inchi:{{input}} OR pharmgkb.inchi:{{input}} OR drugcentral.structures.inchi:{{input}} OR drugbank.inchi:{{input}} OR chembl.inchi:{{input}} OR chebi.inchi:{{input}}
            'http://identifiers.org/uniprot/':
              /query?q=chebi.uniprot_database_links:{{input}} OR drugbank.enzymes.uniprot:{{input}} OR drugbank.pathways.enzymes.uniprot-id:{{input}} OR drugbank.pharmacology.snp_adverse_drug_reactions.reaction.uniprot-id:{{input}} OR drugbank.pharmacology.snp_effects.effect.uniprot-id:{{input}} OR drugbank.targets.uniprot:{{input}} OR drugbank.transporters.uniprot:{{input}} OR drugcentral.bioactivity.uniprot_id:{{input}} OR pharmgkb.cross_references.uniprotkb:{{input}}
            
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: _id
              valueType: 'http://identifiers.org/drug.symbol/'
            - path: cadd.gene.genename
              valueType: 'http://identifiers.org/uniprot/'
            - path: clinvar.rsid
              valueType: 'http://identifiers.org/drugbank/'
            - path: cadd.gene.gene_id
              valueType: 'http://identifiers.org/dbsnp/'
            - path: cadd.gene.feature_id
              valueType: 'http://identifiers.org/pubmed/'
            - path: cadd.gene.ccds_id
              valueType: 'http://identifiers.org/clinicaltrials/'
            - path: clinvar.uniprot
              valueType: 'http://identifiers.org/rxcui/'
  '/drug/{drugid}':
    get:
      parameters:
        - name: drugid
          in: path
          description: >-
            DrugBank ID, InCHIKey, CHEBI ID, CHEMBL ID
          required: true
          x-valueType:
            - 'http://identifiers.org/drug.symbol/'
      responses:
        '200':
          content:
            application/json:
              x-responseSchema:
                properties:
                  reporter:
                    properties:
                      HTA-2_0:
                        type: string
                      HG-U133_Plus_2:
                        items:
                          type: string
                        type: array
                      HuEx-1_0:
                        type: integer
                      HuGene-1_1:
                        type: integer
                      HuGene-2_1:
                        type: integer
                      HG-U95Av2:
                        items:
                          type: string
                        type: array
                    type: object
          x-responseValueType:
            - path: cadd.gene.genename
              valueType: 'http://identifiers.org/uniprot/'
            - path: clinvar.rsid
              valueType: 'http://identifiers.org/drugbank/'
            - path: cadd.gene.gene_id
              valueType: 'http://identifiers.org/dbsnp/'
            - path: cadd.gene.feature_id
              valueType: 'http://identifiers.org/pubmed/'
            - path: cadd.gene.ccds_id
              valueType: 'http://identifiers.org/clinicaltrials/'
            - path: clinvar.uniprot
              valueType: 'http://identifiers.org/rxcui/'
