openapi: '3.0'
info:
  version: 1.0
  title: MyChem.info API
  description: >-
    Documentation of the MyChem.info Chemical Query web services. Learn more about
    [MyChem.info](http://mychem.info/)
servers:
  url: 'http://mychem.info/v1'
paths:
  /query:
    get:
      description: Makes chemical query and returns matching chemicals list.
      parameters:
        - name: q
          in: query
          description: >-
            Query string. Examples "Fludara", "CHEMBI:63599", "DB01073". 
          required: true
          x-valueType:
            - 'http://identifiers.org/rxcui/'
            - 'http://identifiers.org/chebi/'
            - 'http://identifiers.org/chembl/'
            - 'http://identifiers.org/drugbank/'
            - 'http://identifiers.org/iuphar.ligand/'
            - 'http://identifiers.org/kegg.drug/'
            - 'http://identifiers.org/kegg.compound/'
            - 'http://identifiers.org/pubchem.compound/'
            - 'http://identifiers.org/unii/'
            - 'http://identifiers.org/inchikey/'
            - 'http://identifiers.org/inchi/'
            - 'http://identifiers.org/uniprot/'
      responses:
        '200':
          x-responseValueType:
            - path: _id
              valueType: 'http://identifiers.org/inchikey/'
            - path: cadd.gene.genename
              valueType: 'http://identifiers.org/uniprot/'
            - path: clinvar.rsid
              valueType: 'http://identifiers.org/drugbank/'
            - path: cadd.gene.gene_id
              valueType: 'http://identifiers.org/dbsnp/'
            - path: cadd.gene.feature_id
              valueType: 'http://identifiers.org/pubmed/'
            - path: cadd.gene.ccds_id
              valueType: 'http://identifiers.org/clinicaltrials/'
            - path: clinvar.uniprot
              valueType: 'http://identifiers.org/rxcui/'
          x-JSONLDContext:
            'https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/jsonld_context/mychem_context.json'
  '/drug/{drugid}':
    get:
      parameters:
        - name: drugid
          in: path
          description: >-
            DrugBank ID, InCHIKey, CHEBI ID, CHEMBL ID
          required: true
          x-valueType:
            - 'http://identifiers.org/inchikey/'
      responses:
        '200':
          content:
          x-responseValueType:
            - path: cadd.gene.genename
              valueType: 'http://identifiers.org/uniprot/'
            - path: clinvar.rsid
              valueType: 'http://identifiers.org/drugbank/'
            - path: cadd.gene.gene_id
              valueType: 'http://identifiers.org/dbsnp/'
            - path: cadd.gene.feature_id
              valueType: 'http://identifiers.org/pubmed/'
            - path: cadd.gene.ccds_id
              valueType: 'http://identifiers.org/clinicaltrials/'
            - path: clinvar.uniprot
              valueType: 'http://identifiers.org/rxcui/'
          x-JSONLDContext:
            'https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/jsonld_context/mychem_context.json'