api: EXAMPLE API                # REQUIRED. Name of your API
openapi: ./exampleapi.json      # REQUIRED. PATH to the OpenAPI metadata in JSON/YAML format. You can copy from smart-api registry for example.
translator:                     # this section lists metadata related to translator project
  returnjson: true              # put 'true' if the API returns JSON output
  also_available_in: []         # specify whether the data provided by EXAMPLE API is also included in other API(s)
  notes:                        # other features specific for EXAMPLE API
endpoints:                      # this section lists all endpoints for EXAMPLE API. Required for APIs integrated in API explorer.
- url_syntax: http://EXAMPLEAPI/ENDPOINT1/{{input}} # URL query syntax for ENDPOINT 1, 
  input:                        # the input type(s) supported by the ENDPOINT 1. 
  # change to URI
  - http://identifiers.org/###/ # use URI to speicify the input type.
  output:                       # the output type(s) returned by the ENDPOINT 1.
  - http://identifiers.org/###/ # use URI to speicify the output type.
  - ...
  jsonld: ./jsonld_context/EXAMPLEPAI_ENDPOINT1_context.json # PATH to the JSON-LD context file for ENDPOINT 1
- url_syntax: http://EXAMPLEAPI/ENDPOINT2/{{input}} # add another endpoint if exists
  input:
  - http://identifiers.org/###/
  output:
  - http://identifiers.org/###/
  - ...
  jsonld: ./jsonld_context/EXAMPLEAPI_ENDPOINT2_context.json

sparql:
  # you can add more metadata about your sparql endpoint
  field1:  <value1>

graphql:
  # you can add more metadata about your graphql endpoint
  field1:  <value1>
