api: mygene.info
openapi: ./mygene_openapi.json
translator:
  returnjson: true
  also_available_in: []
  notes: 
endpoints:
- url_syntax: http://mygene.info/v3/gene/{{input}}
  input:
  # change to URI
  - http://identifiers.org/ncbigene/
  output:
  - http://identifiers.org/hgnc.symbol/
  - ensembl_gene_id
  - http://identifiers.org/wikipathways/
  - http://identifiers.org/pubmed/
  - http://identifiers.org/uniprot/
  jsonld: ./jsonld_context/myvgene_context.json
- url_syntax: http://mygene.info/v3/query?q={{input}}&fetch_all=TRUE&fields=_id
  input:
  - http://identifiers.org/hgnc.symbol/
  - ensembl_gene_id
  - http://identifiers.org/wikipathways/
  - http://identifiers.org/pubmed/
  - http://identifiers.org/uniprot/
  - http://identifiers.org/ncbigene/
  output:
  - http://identifiers.org/ncbigene/
  jsonld: ./jsonld_context/mygene_context.json