openapi: '3.0'
info:
  version: 3.0
  title: MyGene.info API
  description: >-
    Documentation of the MyGene.info Gene Query web services. Learn more about
    [MyGene.info](http://mygene.info/)
servers:
  url: 'http://mygene.info/v3'
paths:
  /query:
    get:
      description: Makes gene query and returns matching gene list.
      parameters:
        - name: q
          in: query
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/hgnc.symbol/'
            - 'http://identifiers.org/refseq/'
            - 'http://identifiers.org/unigene/'
            - 'http://identifiers.org/uniprot/'
            - 'http://identifiers.org/pdb/'
            - 'http://identifiers.org/biocarta.pathway/'
            - 'http://identifiers.org/kegg.pathway/'
            - 'http://identifiers.org/wikipathways/'
            - 'http://identifiers.org/pharmgkb.pathways/'
            - 'http://identifiers.org/reactome/'
          x-requestTemplate:
            'http://identifiers.org/hgnc.symbol/':
              symbol:{{input}}
            'http://identifiers.org/refseq/':
              refseq.genomic:{{input}}
            'http://identifiers.org/unigene/':
              unigene:{{input}}
            'http://identifiers.org/uniprot/':
              uniprot.Swiss-Prot:{{input}}
            'http://identifiers.org/pdb/':
              pdb:{{input}}
            'http://identifiers.org/biocarta.pathway/':
              pathway.biocarta.id:{{input}}
            'http://identifiers.org/kegg.pathway/':
              pathway.kegg.id:{{input}}
            'http://identifiers.org/wikipathways/':
              pathway.wikipathways.id:{{input}}
            'http://identifiers.org/pharmgkb.pathways/':
              pathway.pharmgkb.id:{{input}}
            'http://identifiers.org/reactome/':
              pathway.reactome.id:{{input}}
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: hits._id
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
            - path: hits.taxid
              valueType: 'http://identifiers.org/taxonomy/'
    post:
      description: make gene queries in batch 
      parameters:
        - name: q
          in: body
          required: true
          x-valueType:
            - 'http://identifiers.org/hgnc.symbol/'
            - 'http://identifiers.org/refseq/'
            - 'http://identifiers.org/unigene/'
            - 'http://identifiers.org/uniprot/'
            - 'http://identifiers.org/pdb/'
            - 'http://identifiers.org/biocarta.pathway/'
            - 'http://identifiers.org/kegg.pathway/'
            - 'http://identifiers.org/wikipathways/'
            - 'http://identifiers.org/pharmgkb.pathways/'
            - 'http://identifiers.org/reactome/'
          x-batchSupport: true
          x-batchInputType: delimited
          x-batchDelimiter: ','
        - name: scopes
          in: body
          required: true
          x-requestTemplate:
            'default':
              ''
            'http://identifiers.org/hgnc.symbol/':
              symbol
            'http://identifiers.org/refseq/':
              refseq.genomic
            'http://identifiers.org/unigene/':
              unigene
            'http://identifiers.org/uniprot/':
              uniprot.Swiss-Prot
            'http://identifiers.org/pdb/':
              pdb
            'http://identifiers.org/biocarta.pathway/':
              pathway.biocarta.id
            'http://identifiers.org/kegg.pathway/':
              pathway.kegg.id
            'http://identifiers.org/wikipathways/':
              pathway.wikipathways.id
            'http://identifiers.org/pharmgkb.pathways/':
              pathway.pharmgkb.id
            'http://identifiers.org/reactome/':
              pathway.reactome.id
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: hits._id
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
            - path: hits.taxid
              valueType: 'http://identifiers.org/taxonomy/'
  '/gene/{geneid}':
    get:
      parameters:
        - name: geneid
          in: path
          description: >-
            Entrez or Ensembl gene id, e.g., 1017, ENSG00000170248. A retired
            Entrez Gene id works too if it is replaced by a new one, e.g.,
            245794
          required: true
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/ensembl/'
          x-requestTemplate:
            'http://identifiers.org/ncbigene/':
              /gene/{{input}}
            'http://identifiers.org/ensembl/':
              /gene/{{input}}           
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: symbol
              valueType: 'http://identifiers.org/hgnc.symbol'
            - path: unigene
              valueType: 'http://identifiers.org/unigene/'
            - path: uniprot.Swiss-Prot
              valueType: 'http://identifiers.org/uniprot/'
            - path: pdb
              valueType: 'http://identifiers.org/pdb/'
            - path: pathway.biocarta.id
              valueType: 'http://identifiers.org/biocarta.pathway/'
            - path: pathway.kegg.id
              valueType: 'http://identifiers.org/kegg.pathway/'
            - path: pathway.reactome.id
              valueType: 'http://identifiers.org/reactome/'
            - path: pathway.wikipathways.id
              valueType: 'http://identifiers.org/wikipathways/'
            - path: pathway.pharmgkb.id
              valueType: 'http://identifiers.org/pharmgkb.pathways/'
    post:
      parameters:
        - name: ids
          in: body
          required: true
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/ensembl/'
          x-batchSupport: true
          x-batchInputType: delimited
          x-batchDelimiter: ','
        - name: species
          in: body
          required: false
          x-valueType:
            - 'http://identifiers.org/taxonomy/'
          x-valueDefault: all
          x-batchSupport: true
          x-batchInputType: delimited
          x-batchDelimiter: ','
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: symbol
              valueType: 'http://identifiers.org/hgnc.symbol'
            - path: unigene
              valueType: 'http://identifiers.org/unigene/'
            - path: uniprot.Swiss-Prot
              valueType: 'http://identifiers.org/uniprot/'
            - path: pdb
              valueType: 'http://identifiers.org/pdb/'
            - path: pathway.biocarta.id
              valueType: 'http://identifiers.org/biocarta.pathway/'
            - path: pathway.kegg.id
              valueType: 'http://identifiers.org/kegg.pathway/'
            - path: pathway.reactome.id
              valueType: 'http://identifiers.org/reactome/'
            - path: pathway.wikipathways.id
              valueType: 'http://identifiers.org/wikipathways/'
            - path: pathway.pharmgkb.id
              valueType: 'http://identifiers.org/pharmgkb.pathways/'
