openapi: '3.0'
info:
  version: 3.0
  title: MyGene.info API
  description: >-
    Documentation of the MyGene.info Gene Query web services. Learn more about
    [MyGene.info](http://mygene.info/)
servers:
  url: 'http://mygene.info/v3'
paths:
  /query:
    get:
      description: Makes gene query and returns matching gene list.
      parameters:
        - name: q
          in: query
          description: >-
            Query string. Examples "CDK2", "NM_052827", "204639_at". The
            detailed query syntax can be found at
            http://docs.mygene.info/en/latest/doc/query_service.html
          required: true
          x-valueType:
            - 'http://identifiers.org/hgnc.symbol/'
            - 'http://identifiers.org/refseq/'
            - 'http://identifiers.org/unigene/'
            - 'http://identifiers.org/uniprot/'
            - 'http://identifiers.org/pdb/'
            - 'http://identifiers.org/biocarta.pathway/'
            - 'http://identifiers.org/kegg.pathway/'
            - 'http://identifiers.org/wikipathways/'
            - 'http://identifiers.org/pharmgkb.pathways/'
            - 'http://identifiers.org/reactome/'
          x-requestTemplate:
            'http://identifiers.org/hgnc.symbol/':
              /query?q=symbol:{{input}}
            'http://identifiers.org/refseq/':
              - /query?q=refseq.genomic:{{input}}
              - /query?q=refseq.protein:{{input}}
              - /query?q=refseq.rna:{{input}}
              - /query?q=refseq.translation.protein:{{input}}
              - /query?q=refseq.translation.rna:{{input}}
            'http://identifiers.org/unigene/':
              /query?q=unigene:{{input}}
            'http://identifiers.org/uniprot/':
              /query?q=uniprot.Swiss-Prot:{{input}}
            'http://identifiers.org/pdb/':
              /query?q=pdb:{{input}}
            'http://identifiers.org/biocarta.pathway/':
              /query?q=pathway.biocarta.id:{{input}}
            'http://identifiers.org/kegg.pathway'
              /query?q=pathway.kegg.id:{{input}}
            'http://identifiers.org/wikipathways/':
              /query?q=pathway.wikipathways.id:{{input}}
            'http://identifiers.org/pharmgkb.pathways/':
              /query?q=pathway.pharmgkb.id:{{input}}
            'htpp://identifiers.org/reactome/':
              /query?q=pathway.reactome.id:{{input}}
      responses:
        '200':
          content:
            application/json:
              x-responseProfile: 'http://www.w3.org/ns/anno.jsonld'
          x-responseValueType:
            - path: hits._id
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: hits.symbol
              valueType: 'http://identifiers.org/hgnc.symbol/'
            - path: hits.taxid
              valueType: 'http://identifiers.org/taxonomy/'
  '/gene/{geneid}':
    get:
      parameters:
        - name: geneid
          in: path
          description: >-
            Entrez or Ensembl gene id, e.g., 1017, ENSG00000170248. A retired
            Entrez Gene id works too if it is replaced by a new one, e.g.,
            245794
          required: true
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/ensembl/'
      responses:
        '200':
          content:
            application/json:
              x-responseSchema:
                properties:
                  reporter:
                    properties:
                      HTA-2_0:
                        type: string
                      HG-U133_Plus_2:
                        items:
                          type: string
                        type: array
                      HuEx-1_0:
                        type: integer
                      HuGene-1_1:
                        type: integer
                      HuGene-2_1:
                        type: integer
                      HG-U95Av2:
                        items:
                          type: string
                        type: array
                    type: object
          x-responseValueType:
            - path: ec
              valueType: 'http://identifiers.org/ec-code/'
            - path: ensembl.gene
              valueType: 'http://identifiers.org/ensembl/'
            - path: ensembl.translation.protein
              valueType: 'http://identifiers.org/ensembl/'
            - path: ensembl.translation.rna
              valueType: 'http://identifiers.org/ensembl/'
            - path: entrezgene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: generif.pubmed
              valueType: 'http://identifiers.org/pubmed/'