api: myvariant.info
openapi: ./myvariant_openapi.json
translator:
  returnjson: true
  also_available_in: []
  notes: 
endpoints:
- url_syntax: http://myvariant.info/v1/query?q={{input}}&fetch_all=TRUE&fields=_id
  input:
  # change to URI
  - http://identifiers.org/ncbigene/
  - http://identifiers.org/hgnc.symbol/
  - ensembl_gene_id
  - http://identifiers.org/dbsnp/
  - http://identifiers.org/pubmed/
  - http://identifiers.org/uniprot/
  output:
  - hgvs_id
  jsonld: ./jsonld_context/myvariant_context.json
- url_syntax: http://myvariant.info/v1/variant/{{input}}
  input:
  - hgvs_id
  output:
  - http://identifiers.org/ncbigene/
  - http://identifiers.org/hgnc.symbol/
  - ensembl_gene_id
  - http://identifiers.org/dbsnp/
  - http://identifiers.org/pubmed/
  - http://identifiers.org/uniprot/
  jsonld: ./jsonld_context/myvariant_context.json