# Schema for proposed extensions to the API_LIST.yaml API metadata format
# https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/API_LIST.yml


properties:

  smartAPImetadata:
    description: Relative path to the smartAPI yaml description of the API in the translator-api-registry repo.
    type: string
    example: biolink/openapi.yaml
    example: mygene.info/openapi_full.yml

  apiName:
    description: A name for the API.
    type: string
    example: "Monarch-Biolink API"
 
  accessURL:
    description: The URL where the API service/endpoint can be programmatically accessed/queried.
    type: string
    format: url
    example: "https://api.monarchinitiative.org/api/"

  serviceType:
    description: Whether the API provides data or computational services (i.e. does it serve pre-indexed data in response to a user query, or does it perform computation on input data to generate novel output)
    type:  array
    items:  [data, computation] ($ENUM1)
    example: [data]

    contentDescription:
    description: Brief free-text description of content/scope of data served by the API, and the source/provenance of the data. Can include a link to existing documentation.
    type: string
    example: "The Biolink API serves data from a neo4j graph database holding semantically integrated data from a variety of biological/biomedical community databases, with a focus on genotype-phenotype related resources. Most data represents manually-curated knowledge derived from the published literature or research studies. For more see https://monarchinitiative.org/page/about."

  dataLevel:
    description: The general category/level of data provided or operated on by the API.  For definitions of allowable values, see description in VALUE SET ENUMERATIONS section below.
    type:  array 
    items: [experimental data, computed data, curated data, EHR/patient data, ontologies] ($ENUM2)
    example: [curated data]

   primarySources:  	
    description: This field is relevant only for APIs that serve data aggregated from external sources (e.g. Biothings, Biolink, Wikidata), or that compute over data from external sources to generate outputs served by the API (e.g. BigGIM). In this field, provide the names of all such external knowledge sources, or a link to documentation listing such sources. 
    type: string
    format: comma separated list of source names, or link to external list
    example: "MGI, ZFIN, ClinVar"
    example: "See list at https://monarchinitiative.org/about/sources"
 
  entityTypes:
    description: The types of entities described by data provided or operated on by the API.
    type: array 
    items: For allowable values here, see ENUM3 in the VALUE SET ENUMERATIONS section below ($ENUM3)
    example: [Gene, Disease, Phenotype]
 
  entityAssociationTypes:
  	description: If the API returns 'associations' between domain entities, list pairs/sets of entity types that are directly connected in the data it serves. These can be pre-indexed associations (e.g. Biolink, Wikidata), or algorithmically computed associations (e.g. BigGIM). Note that this field may not be relevant for APIs that don’t serve such 'associations', such as those serving EHR data, experimental measurements, exposure data, etc.
    type: array 
    items: hyphen-separated pairs of terms, each of which is an entity type from $ENUM3
    example: [Gene - Phenotype, Gene - Disease, Disease - Phenotype, Drug - Protein]

  entityAttributeTypes:
    description:  The types of attributes or data types that an API returns about the entities it describes. This field records entity-datatype associations, as opposed to entity-entity associations captured by the entityAssociationTypes field. 
    type: array
    items: hyphen-separated pairs of terms. The first is an entity type from $ENUM3, and the second is a user-defined attribute or data type.
    example: [Variant/Allele - frequency] 
    example: [SequenceFeature - sequence, SequenceFeature - genomic position, Gene - conservation score] 
    example: [Patient - exposure score]

  translatorTeam:
    description: Translator team(s) that generated or manage the API/Service.
    type: array 
    items: [Purple, Orange, Green, Blue, Grey, Red, External]  ($ENUM4)
    example: [Orange]

  license:
    description: The name of a specific license for data served by the API, or link to web page describing licensing information.
    type: string
    example: "CC-BY-3.0"

  termsOfService:
    description:  URL linking to to a description of the terms of service for the API, including intended use and disclaimers. 
    type: string
    format: url 
    example: "http://mygene.info/terms/"

  accessRestriction:
    description: whether there are restrictions to using the API.
    type: array
    items: [none, limited, fee] ($ENUM5)
    example: [none]

  returrnsjson:
    description: Whether the  API returns  data in JSON format.
    type: boolean
    example: true

###############################################################################

# VALUE SET ENUMERATIONS
  # Further description of the five value sets defined above are provided below.
  # Note that the boolean 'extensible' field indicates if/how users are able to extend value sets with new terms.  
  # A 'true' value indicates that any user can extend as needed without review/vetting by others (i.e. directly edit and commit the value set in this document). A 'false' indicates a closed value set where the addition of new terms must be vetted by the wider community (i.e. post a issue in the Github tracker requesting the new value, or submit proposed changes via a pull request).

valueSetEnumerations: 

  - id: ENUM1 
    name: API Service Types
    description: Terms to describe if an API returns data or performs computation on input data
    extensible: false 
    values:
      - data
      - computation
 
  - id: ENUM2
    name: Data Levels
    description: terms describe high-level category/level of data provided or operated on by the resource
    extensible: false
    values:
      - experimental data
          definition: experimental or measurement data submitted by researchers/data collection efforts. May be raw, processed data, or summarized to standardize or annotate with metadata - e.g.omics data, air quality/exposure data.
      - computed data
          definition: data generated through computation/inference using more fundamental input data, as performed by the providers of the API (e.g. Blue team gene-associations derived from expression and interaction data)
      - curated data
          definition: higher-order assertions generated through literature curation, inference, or computation over more primitive data (e.g. GO annotations, protein interactions, G2P associations)
      - EHR/patient data
          definition: patient/case level assertions or clinical data
      - ontologies
          definition: knowledge structured as ontologies - manually asserted or data derived
 
  - id: ENUM3
    name: Entity Types
    description: The types of entities described by data that is provided by or operated on by the API. Hierarchical organization is simply means to facilitate finding terms by provide useful groupings/categories. It is not meant to represent an ontological hierarchy.
    extensible: true
    values:
      - SequenceEntity
        - Gene
        - Allele/Variant
        - Genotype
        - Protein
        - RNA
        - ProteinDomain
        - ProteinModification
        - EpigeneticModification
        - Operon
        - Homolog*
        - DrugTarget*
      - ChemicalEntity
        - Substance
        - SmallMolecule
        - Metabolite
        - PharmaceuticalProduct
        - ChemicalReagent*
        - Drug*
      - PhysicalCondition
        - Trait
        - Phenotype
        - Disease
        - SideEffect*
      - ModelSystem
        - Organism/Strain
        - CellLine
        - Xenograft
      - SocioenvironmentalExposure
        - ChemicalExposure
        - Behavior
        - SocioEconomicFactor
        - GeographicalLocation
      - AnatomicalEntity
        - Tissue/Organ
        - Cell
        - CellComponent
      - BiologicalProcess
        - MolecularInteraction
        - Reaction
        - Pathway
        - DevelopmentalStage
      - GOTerm
        - MolecularFunction
        - CellComponent
        - BiologicalProcess
      - Study
        - ExperimentalStudy
        - ClinicalStudy
      - ResearchResource
        - Antibody
        - GeneKnockdownReagent
        - Construct
        - Biospecimen
        - ModelSystem
        - ChemicalReagent*
      - InformationResource
        - Identifier
        - DataModel
        - Ontology
        - Database
        - Protocol
        - Publication
        - ClinicalReport
      - ClinicalEntity
        - Patient/Case
        - PharmaceuticalProduct
        - ClinicalReport
        - Diagnosis
        - Outcome
        - Stratification/Endotype
      - ClinicalEvent
        - ClinicalEncounter
        - Treatment/Therapy
        - Drug Response
        - AdverseEvent

     # Note that asterisks mark entities that are really context dependent "roles" played by some physical entity (e.g. a ChemicalEntity that is a drug, or a Gene that is a homolog)
  

  - id: ENUM4
    name: Translator Teams
    description: the team or teams developed or manage the API
    extensible: false
    values:
      - Purple
      - Orange
      - Green
      - Blue
      - Grey
      - Red
      - External
  
  - id: ENUM5
    name: Access Restrictions
    description: terms describing any restrictions on use on an API
    extensible: false
    values:
      - none
      - limited
      - fee
 


